# Generated by Django 4.2.25 on 2025-10-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('ebook', 'E-Book'), ('audiobook', 'Audiobook')], default='hardcover', max_length=12),
        ),
    ]
